version: '3.4'
services:
  geocoder:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    image: geocoder
    ports:
      - $HOST_POSTGRES_PORT:5432
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    command: [ "postgres", "-c", "max_wal_size=2GB" ]
